# Generated by Django 3.2.18 on 2023-03-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='title',
        ),
    ]
